### ISSUE TITLE
FeatureRequest: Make it a chrome extension too - or website?

### ISSUE THREAD

**Issue by worthy7** [zvxr-tech/email-dot-tracker#1]
Looks like a great project, I was just looking at something similar.
If this was a chrome and firefox extension, then it could also be extended to parse any email addresses on a page (so, when looking at our email client like gmail) and automatically translate those addresses into the "source website" version:

"t...e.s...t@gmail.com" -> test@gmail.com - from www.spammysite.com

**Comment by zvxr-tech** [comment]
Thanks Worthy7!
This project was just an excuse for me to dabble with web extensions. Unfortunately, gmail has since stopped supporting multiple runs of the period delimiter (I.e. "y...ou@gmail.com), as well as leading and trailing delimiters, so this project is somewhat deprecated. The ability to have runs of delimiters is what allows for a broad encoding space and without it the extension is restricted to a smaller number of encodings. For this reason, I probably won't be extending my project -- but feel free to fork and build off of it.

Cheers.
